### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by liamxg** [abschneider/phylogeography-density-plots#1]
> source('bayesian_functions.R')
Error in value[[3L]](cond) : 
  Package ‘knitr’ version 1.30 cannot be unloaded:
 Error in unloadNamespace(package) : namespace ‘knitr’ is imported by ‘rmarkdown’ so cannot be unloaded

could you please help me out?

**Comment by liamxg** [comment]
rateextract(logfile,burninpercentage,locations,traitname)
[1] "Loading data..."
[1] "Removing burn-in..."
[1] "Creating empty matrix..."
[1] "Extracting rates and indicators from logfile..."
 Error: Must rename columns with a valid subscript vector.
x Subscript has the wrong type `xfun_raw_string`.
ℹ It must be numeric or character.
Run `rlang::last_error()` to see where the error occurred.

**Comment by abschneider** [comment]
Try unloading 'rmarkdown' first and then rerunning the functions. Also, can you please provide the log file you have used or a sample using dummy data?

**Comment by abschneider** [comment]
Also, if you try with the example data, your rate extract function should read something like this:
rateextract("example_phylogeo.log",20,locations,"City")

Where 20 = a burning percentage I selected;
Locations is actually locations = read_lines("example_locations.txt"), a list of the 13 cities from the example file;
and "City" is the label of the traitname found on the logfile.

**Comment by liamxg** [comment]
> resultsDir = './Example_files/'
> exampleDir = paste(resultsDir)	
> logfile = paste(exampleDir,"example_phylogeo.log",sep='')
> burninpercentage = 10
> locations = scan(paste(exampleDir,"example_locations.txt",sep=''),what="", sep="\n")
Read 13 items
> traitname = "City" #Name trait of interest
> rateextract(logfile,burninpercentage,locations,traitname)
[1] "Loading data..."
[1] "Removing burn-in..."
[1] "Creating empty matrix..."
[1] "Extracting rates and indicators from logfile..."
 Error: Must rename columns with a valid subscript vector.
x Subscript has the wrong type `xfun_raw_string`.
ℹ It must be numeric or character.
Run `rlang::last_error()` to see where the error occurred.

**Comment by liamxg** [comment]
use your data and code, still not work.
